services:
  web:
    image: ghcr.io/randriamasinoro/resto-site:latest
    container_name: resto-site
    ports:
      - "8001:80"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"